spring.cloud.config.uri: http://localhost:8888

server:
  port: 8443

#eureka:
#  client:
#    registryFetchIntervalSeconds: 5
#    serviceUrl:
#      defaultZone: http://127.0.0.1:8761/eureka/
#  instance:
#    leaseRenewalIntervalInSeconds: 10
#    leaseExpirationDurationInSeconds: 30
#    preferIpAddress: true

# Spring Boot datasource configuration
spring:
  datasource:
    initialize: true
    url: jdbc:hsqldb:mem:oauth2
#    username: DEV01_OAUTH_SEC_APP
#    password: "DEV01_OAUTH_SEC_APP#765"
    driver-class-name: org.hsqldb.jdbcDriver
    continue-on-error: true
 #   validation-query: SELECT 1 FROM DUAL
    initial-size: 5
    max-active: 10
    max-idle: 5
    min-idle: 2
    test-on-borrow: false
    remove-abandoned: true

---
spring.profiles: prod

spring.main.show_banner: false

server.tomcat:
  access-log-enabled: true
  access-log-pattern: "%{X-Forwarded-For}i %l %u %t %r %s %b %{User-Agent}i %{Referer}i - %T"
  basedir: /var/log/inka/tomcat

# Endpoints - turn off in production environment
endpoints:
  autoconfig.enabled: false
  beans.enabled: false
  configprops.enabled: false
  dump.enabled: false
  env.enabled: false
  health.enabled: true
  info.enabled: true
  metrics.enabled: false
  mappings.enabled: false
  restart.enable: false
  shutdown.enabled: false
  trace.enabled: false